[package]
name = "grime"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
